/****************************************************************************
**
** Namespace EXCOMLib generated by dumpcpp from type library
** C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.ocx
**
****************************************************************************/

#ifndef QAX_DUMPCPP_EXCOMLIB_H
#define QAX_DUMPCPP_EXCOMLIB_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef EXCOMLIB_EXPORT
#define EXCOMLIB_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace EXCOMLib {


class EXCOMLIB_EXPORT _DeXCom : public QAxObject
{
public:
    _DeXCom(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property Block

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Block() const; //Returns the value of Block
    inline void SetBlock(int value); //Sets the value of the Block property

    /*
    Property DeviceID

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int DeviceID() const; //Returns the value of DeviceID
    inline void SetDeviceID(int value); //Sets the value of the DeviceID property

    /*
    Property Ebit

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Ebit() const; //Returns the value of Ebit
    inline void SetEbit(int value); //Sets the value of the Ebit property

    /*
    Property Function

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Function() const; //Returns the value of Function
    inline void SetFunction(int value); //Sets the value of the Function property

    /*
    Property HeaderSize

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int HeaderSize() const; //Returns the value of HeaderSize
    inline void SetHeaderSize(int value); //Sets the value of the HeaderSize property

    /*
    Property MsgSize

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int MsgSize() const; //Returns the value of MsgSize
    inline void SetMsgSize(int value); //Sets the value of the MsgSize property

    /*
    Property PType

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int PType() const; //Returns the value of PType
    inline void SetPType(int value); //Sets the value of the PType property

    /*
    Property Rbit

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Rbit() const; //Returns the value of Rbit
    inline void SetRbit(int value); //Sets the value of the Rbit property

    /*
    Property SType

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SType() const; //Returns the value of SType
    inline void SetSType(int value); //Sets the value of the SType property

    /*
    Property Stream

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Stream() const; //Returns the value of Stream
    inline void SetStream(int value); //Sets the value of the Stream property

    /*
    Property SystemBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SystemBytes() const; //Returns the value of SystemBytes
    inline void SetSystemBytes(int value); //Sets the value of the SystemBytes property

    /*
    Property Wbit

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Wbit() const; //Returns the value of Wbit
    inline void SetWbit(int value); //Sets the value of the Wbit property

    /*
    Method Close

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Close();

    /*
    Method CloseSecsMsg

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline void CloseSecsMsg(int lMsgId);

    /*
    Method DebugInfo

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int DebugInfo(int& pnInfo);

    /*
    Method EnableLog

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int EnableLog(int nLogType, int nEnabled);

    /*
    Method GeneralCall

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GeneralCall(int lMsgId, int nDispatchId, int lpDispatchData, int lDispatchArg1, int lDispatchArg2);

    /*
    Method GetAlarmMsgInfo

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetAlarmMsgInfo(int lMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit);

    /*
    Method GetAsciiItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetAsciiItem(int lMsgId, QString& psValue, int& plCount);

    /*
    Method GetBinaryItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetBinaryItem(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetBoolItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetBoolItem(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetCurrentItemCount

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetCurrentItemCount(int lMsgId);

    /*
    Method GetCurrentItemType

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetCurrentItemType(int lMsgId);

    /*
    Method GetF4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetF4Item(int lMsgId, double& prValue, int& plCount, int lSize);

    /*
    Method GetF8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetF8Item(int lMsgId, double& prValue, int& plCount, int lSize);

    /*
    Method GetHeaderBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetHeaderBytes(int lMsgId, int& pnHeader, int nSize);

    /*
    Method GetI1Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetI1Item(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetI2Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetI2Item(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetI4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetI4Item(int lMsgId, int& plValue, int& plCount, int lSize);

    /*
    Method GetI8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetI8Item(int lMsgId, int& plValue, int& plCount, int lSize);

    /*
    Method GetInvalidMsgInfo

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetInvalidMsgInfo(int lMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit);

    /*
    Method GetJis8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetJis8Item(int lMsgId, QString& psValue, int& plCount);

    /*
    Method GetListItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetListItem(int lMsgId, int& pnItems);

    /*
    Method GetMsgBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetMsgBytes(int lMsgId, int& pnMsg, int lSize);

    /*
    Method GetParam

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline QString GetParam(const QString& pszParamName);

    /*
    Method GetSecsLog

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline QString GetSecsLog(int lMsgId);

    /*
    Method GetStringItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline QString GetStringItem(int lMsgId, int& plCount);

    /*
    Method GetSysBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetSysBytes(int lMsgId);

    /*
    Method GetU1Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetU1Item(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetU2Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetU2Item(int lMsgId, int& plValue, int& plCount, int lSize);

    /*
    Method GetU4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetU4Item(int lMsgId, double& prValue, int& plCount, int lSize);

    /*
    Method GetU8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetU8Item(int lMsgId, double& prValue, int& plCount, int lSize);

    /*
    Method Initialize

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Initialize(const QString& sCfgFile);

    /*
    Method LoadSecsMsg

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int LoadSecsMsg(int& plMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit);

    /*
    Method MakeSecsMsg

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int MakeSecsMsg(int& plMsgId, int nDevId, int nStrm, int nFunc, int lSysByte);

    /*
    Method MakeSpoolStream

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int MakeSpoolStream(int lMsgId);

    /*
    Method ProcExternalStream

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int ProcExternalStream(int& pnMsg, int lSize);

    /*
    Method Send

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Send(int lMsgId);

    /*
    Method SetAsciiFillSpace

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetAsciiFillSpace(int nVal);

    /*
    Method SetAsciiItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetAsciiItem(int lMsgId, const QString& pszValue, int lCount);

    /*
    Method SetBinaryItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetBinaryItem(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetBoolItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetBoolItem(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetF4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetF4Item(int lMsgId, double& prValue, int lCount);

    /*
    Method SetF8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetF8Item(int lMsgId, double& prValue, int lCount);

    /*
    Method SetHeaderBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetHeaderBytes(int lMsgId, int& pnHeader, int nSize);

    /*
    Method SetI1Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetI1Item(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetI2Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetI2Item(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetI4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetI4Item(int lMsgId, int& plValue, int lCount);

    /*
    Method SetI8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetI8Item(int lMsgId, int& plValue, int lCount);

    /*
    Method SetJis8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetJis8Item(int lMsgId, const QString& pszValue, int lCount);

    /*
    Method SetListItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetListItem(int lMsgId, int nItems);

    /*
    Method SetMsgBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetMsgBytes(int lMsgId, int& pnMsg, int lSize);

    /*
    Method SetParam

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetParam(const QString& psParamName, const QString& psVal);

    /*
    Method SetStringItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetStringItem(int lMsgId, QString& pbstrValue, int lCount);

    /*
    Method SetU1Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetU1Item(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetU2Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetU2Item(int lMsgId, int& plValue, int lCount);

    /*
    Method SetU4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetU4Item(int lMsgId, double& prValue, int lCount);

    /*
    Method SetU8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetU8Item(int lMsgId, double& prValue, int lCount);

    /*
    Method SetWBit

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetWBit(int lMsgId, int nWBit);

    /*
    Method Start

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Start();

    /*
    Method Stop

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Stop();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// skipping event interface _DeXComEvents

// Actual coclasses
class EXCOMLIB_EXPORT eXCom : public QAxWidget
{
public:
    eXCom(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl("{717b131f-e3dd-4053-87a6-c4e2b2e983c2}");
    }

    /*
    Property Block

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Block() const; //Returns the value of Block
    inline void SetBlock(int value); //Sets the value of the Block property

    /*
    Property DeviceID

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int DeviceID() const; //Returns the value of DeviceID
    inline void SetDeviceID(int value); //Sets the value of the DeviceID property

    /*
    Property Ebit

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Ebit() const; //Returns the value of Ebit
    inline void SetEbit(int value); //Sets the value of the Ebit property

    /*
    Property Function

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Function() const; //Returns the value of Function
    inline void SetFunction(int value); //Sets the value of the Function property

    /*
    Property HeaderSize

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int HeaderSize() const; //Returns the value of HeaderSize
    inline void SetHeaderSize(int value); //Sets the value of the HeaderSize property

    /*
    Property MsgSize

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int MsgSize() const; //Returns the value of MsgSize
    inline void SetMsgSize(int value); //Sets the value of the MsgSize property

    /*
    Property PType

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int PType() const; //Returns the value of PType
    inline void SetPType(int value); //Sets the value of the PType property

    /*
    Property Rbit

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Rbit() const; //Returns the value of Rbit
    inline void SetRbit(int value); //Sets the value of the Rbit property

    /*
    Property SType

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SType() const; //Returns the value of SType
    inline void SetSType(int value); //Sets the value of the SType property

    /*
    Property Stream

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Stream() const; //Returns the value of Stream
    inline void SetStream(int value); //Sets the value of the Stream property

    /*
    Property SystemBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SystemBytes() const; //Returns the value of SystemBytes
    inline void SetSystemBytes(int value); //Sets the value of the SystemBytes property

    /*
    Property Wbit

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Wbit() const; //Returns the value of Wbit
    inline void SetWbit(int value); //Sets the value of the Wbit property

    /*
    Method Close

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Close();

    /*
    Method CloseSecsMsg

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline void CloseSecsMsg(int lMsgId);

    /*
    Method DebugInfo

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int DebugInfo(int& pnInfo);

    /*
    Method EnableLog

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int EnableLog(int nLogType, int nEnabled);

    /*
    Method GeneralCall

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GeneralCall(int lMsgId, int nDispatchId, int lpDispatchData, int lDispatchArg1, int lDispatchArg2);

    /*
    Method GetAlarmMsgInfo

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetAlarmMsgInfo(int lMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit);

    /*
    Method GetAsciiItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetAsciiItem(int lMsgId, QString& psValue, int& plCount);

    /*
    Method GetBinaryItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetBinaryItem(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetBoolItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetBoolItem(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetCurrentItemCount

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetCurrentItemCount(int lMsgId);

    /*
    Method GetCurrentItemType

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetCurrentItemType(int lMsgId);

    /*
    Method GetF4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetF4Item(int lMsgId, double& prValue, int& plCount, int lSize);

    /*
    Method GetF8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetF8Item(int lMsgId, double& prValue, int& plCount, int lSize);

    /*
    Method GetHeaderBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetHeaderBytes(int lMsgId, int& pnHeader, int nSize);

    /*
    Method GetI1Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetI1Item(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetI2Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetI2Item(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetI4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetI4Item(int lMsgId, int& plValue, int& plCount, int lSize);

    /*
    Method GetI8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetI8Item(int lMsgId, int& plValue, int& plCount, int lSize);

    /*
    Method GetInvalidMsgInfo

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetInvalidMsgInfo(int lMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit);

    /*
    Method GetJis8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetJis8Item(int lMsgId, QString& psValue, int& plCount);

    /*
    Method GetListItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetListItem(int lMsgId, int& pnItems);

    /*
    Method GetMsgBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetMsgBytes(int lMsgId, int& pnMsg, int lSize);

    /*
    Method GetParam

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline QString GetParam(const QString& pszParamName);

    /*
    Method GetSecsLog

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline QString GetSecsLog(int lMsgId);

    /*
    Method GetStringItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline QString GetStringItem(int lMsgId, int& plCount);

    /*
    Method GetSysBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetSysBytes(int lMsgId);

    /*
    Method GetU1Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetU1Item(int lMsgId, int& pnValue, int& plCount, int lSize);

    /*
    Method GetU2Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetU2Item(int lMsgId, int& plValue, int& plCount, int lSize);

    /*
    Method GetU4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetU4Item(int lMsgId, double& prValue, int& plCount, int lSize);

    /*
    Method GetU8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int GetU8Item(int lMsgId, double& prValue, int& plCount, int lSize);

    /*
    Method Initialize

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Initialize(const QString& sCfgFile);

    /*
    Method LoadSecsMsg

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int LoadSecsMsg(int& plMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit);

    /*
    Method MakeSecsMsg

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int MakeSecsMsg(int& plMsgId, int nDevId, int nStrm, int nFunc, int lSysByte);

    /*
    Method MakeSpoolStream

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int MakeSpoolStream(int lMsgId);

    /*
    Method ProcExternalStream

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int ProcExternalStream(int& pnMsg, int lSize);

    /*
    Method Send

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Send(int lMsgId);

    /*
    Method SetAsciiFillSpace

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetAsciiFillSpace(int nVal);

    /*
    Method SetAsciiItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetAsciiItem(int lMsgId, const QString& pszValue, int lCount);

    /*
    Method SetBinaryItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetBinaryItem(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetBoolItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetBoolItem(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetF4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetF4Item(int lMsgId, double& prValue, int lCount);

    /*
    Method SetF8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetF8Item(int lMsgId, double& prValue, int lCount);

    /*
    Method SetHeaderBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetHeaderBytes(int lMsgId, int& pnHeader, int nSize);

    /*
    Method SetI1Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetI1Item(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetI2Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetI2Item(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetI4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetI4Item(int lMsgId, int& plValue, int lCount);

    /*
    Method SetI8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetI8Item(int lMsgId, int& plValue, int lCount);

    /*
    Method SetJis8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetJis8Item(int lMsgId, const QString& pszValue, int lCount);

    /*
    Method SetListItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetListItem(int lMsgId, int nItems);

    /*
    Method SetMsgBytes

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetMsgBytes(int lMsgId, int& pnMsg, int lSize);

    /*
    Method SetParam

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetParam(const QString& psParamName, const QString& psVal);

    /*
    Method SetStringItem

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetStringItem(int lMsgId, QString& pbstrValue, int lCount);

    /*
    Method SetU1Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetU1Item(int lMsgId, int& pnValue, int lCount);

    /*
    Method SetU2Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetU2Item(int lMsgId, int& plValue, int lCount);

    /*
    Method SetU4Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetU4Item(int lMsgId, double& prValue, int lCount);

    /*
    Method SetU8Item

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetU8Item(int lMsgId, double& prValue, int lCount);

    /*
    Method SetWBit

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int SetWBit(int lMsgId, int nWBit);

    /*
    Method Start

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Start();

    /*
    Method Stop

    For more information, see help context 0 in C:\Program Files (x86)\IT Innovation\XCom v2.x\SE\Bin\eXCom.hlp.
    */
    inline int Stop();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_EXCOMLIB_NOINLINES
inline int _DeXCom::Block() const
{
    QVariant qax_result = property("Block");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetBlock(int value){ setProperty("Block", QVariant(value)); }

inline int _DeXCom::DeviceID() const
{
    QVariant qax_result = property("DeviceID");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetDeviceID(int value){ setProperty("DeviceID", QVariant(value)); }

inline int _DeXCom::Ebit() const
{
    QVariant qax_result = property("Ebit");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetEbit(int value){ setProperty("Ebit", QVariant(value)); }

inline int _DeXCom::Function() const
{
    QVariant qax_result = property("Function");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetFunction(int value){ setProperty("Function", QVariant(value)); }

inline int _DeXCom::HeaderSize() const
{
    QVariant qax_result = property("HeaderSize");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetHeaderSize(int value){ setProperty("HeaderSize", QVariant(value)); }

inline int _DeXCom::MsgSize() const
{
    QVariant qax_result = property("MsgSize");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetMsgSize(int value){ setProperty("MsgSize", QVariant(value)); }

inline int _DeXCom::PType() const
{
    QVariant qax_result = property("PType");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetPType(int value){ setProperty("PType", QVariant(value)); }

inline int _DeXCom::Rbit() const
{
    QVariant qax_result = property("Rbit");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetRbit(int value){ setProperty("Rbit", QVariant(value)); }

inline int _DeXCom::SType() const
{
    QVariant qax_result = property("SType");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetSType(int value){ setProperty("SType", QVariant(value)); }

inline int _DeXCom::Stream() const
{
    QVariant qax_result = property("Stream");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetStream(int value){ setProperty("Stream", QVariant(value)); }

inline int _DeXCom::SystemBytes() const
{
    QVariant qax_result = property("SystemBytes");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetSystemBytes(int value){ setProperty("SystemBytes", QVariant(value)); }

inline int _DeXCom::Wbit() const
{
    QVariant qax_result = property("Wbit");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void _DeXCom::SetWbit(int value){ setProperty("Wbit", QVariant(value)); }

inline int _DeXCom::Close()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 7, _a);
    return qax_result;
}

inline void _DeXCom::CloseSecsMsg(int lMsgId)
{
    void *_a[] = {0, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline int _DeXCom::DebugInfo(int& pnInfo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pnInfo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int _DeXCom::EnableLog(int nLogType, int nEnabled)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nLogType, (void*)&nEnabled};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline int _DeXCom::GeneralCall(int lMsgId, int nDispatchId, int lpDispatchData, int lDispatchArg1, int lDispatchArg2)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&nDispatchId, (void*)&lpDispatchData, (void*)&lDispatchArg1, (void*)&lDispatchArg2};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline int _DeXCom::GetAlarmMsgInfo(int lMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnDevId, (void*)&pnStrm, (void*)&pnFunc, (void*)&plSysByte, (void*)&pnWbit};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline int _DeXCom::GetAsciiItem(int lMsgId, QString& psValue, int& plCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&psValue, (void*)&plCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int _DeXCom::GetBinaryItem(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int _DeXCom::GetBoolItem(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline int _DeXCom::GetCurrentItemCount(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int _DeXCom::GetCurrentItemType(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int _DeXCom::GetF4Item(int lMsgId, double& prValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int _DeXCom::GetF8Item(int lMsgId, double& prValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int _DeXCom::GetHeaderBytes(int lMsgId, int& pnHeader, int nSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnHeader, (void*)&nSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int _DeXCom::GetI1Item(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline int _DeXCom::GetI2Item(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline int _DeXCom::GetI4Item(int lMsgId, int& plValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline int _DeXCom::GetI8Item(int lMsgId, int& plValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline int _DeXCom::GetInvalidMsgInfo(int lMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnDevId, (void*)&pnStrm, (void*)&pnFunc, (void*)&plSysByte, (void*)&pnWbit};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline int _DeXCom::GetJis8Item(int lMsgId, QString& psValue, int& plCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&psValue, (void*)&plCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline int _DeXCom::GetListItem(int lMsgId, int& pnItems)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnItems};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline int _DeXCom::GetMsgBytes(int lMsgId, int& pnMsg, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnMsg, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}

inline QString _DeXCom::GetParam(const QString& pszParamName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pszParamName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 29, _a);
    return qax_result;
}

inline QString _DeXCom::GetSecsLog(int lMsgId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 30, _a);
    return qax_result;
}

inline QString _DeXCom::GetStringItem(int lMsgId, int& plCount)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 31, _a);
    return qax_result;
}

inline int _DeXCom::GetSysBytes(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 32, _a);
    return qax_result;
}

inline int _DeXCom::GetU1Item(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 33, _a);
    return qax_result;
}

inline int _DeXCom::GetU2Item(int lMsgId, int& plValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 34, _a);
    return qax_result;
}

inline int _DeXCom::GetU4Item(int lMsgId, double& prValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
    return qax_result;
}

inline int _DeXCom::GetU8Item(int lMsgId, double& prValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
    return qax_result;
}

inline int _DeXCom::Initialize(const QString& sCfgFile)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sCfgFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline int _DeXCom::LoadSecsMsg(int& plMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&plMsgId, (void*)&pnDevId, (void*)&pnStrm, (void*)&pnFunc, (void*)&plSysByte, (void*)&pnWbit};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline int _DeXCom::MakeSecsMsg(int& plMsgId, int nDevId, int nStrm, int nFunc, int lSysByte)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&plMsgId, (void*)&nDevId, (void*)&nStrm, (void*)&nFunc, (void*)&lSysByte};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline int _DeXCom::MakeSpoolStream(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline int _DeXCom::ProcExternalStream(int& pnMsg, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pnMsg, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline int _DeXCom::Send(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline int _DeXCom::SetAsciiFillSpace(int nVal)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nVal};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
    return qax_result;
}

inline int _DeXCom::SetAsciiItem(int lMsgId, const QString& pszValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pszValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
    return qax_result;
}

inline int _DeXCom::SetBinaryItem(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
    return qax_result;
}

inline int _DeXCom::SetBoolItem(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
    return qax_result;
}

inline int _DeXCom::SetF4Item(int lMsgId, double& prValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
    return qax_result;
}

inline int _DeXCom::SetF8Item(int lMsgId, double& prValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
    return qax_result;
}

inline int _DeXCom::SetHeaderBytes(int lMsgId, int& pnHeader, int nSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnHeader, (void*)&nSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
    return qax_result;
}

inline int _DeXCom::SetI1Item(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 55, _a);
    return qax_result;
}

inline int _DeXCom::SetI2Item(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 56, _a);
    return qax_result;
}

inline int _DeXCom::SetI4Item(int lMsgId, int& plValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
    return qax_result;
}

inline int _DeXCom::SetI8Item(int lMsgId, int& plValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 58, _a);
    return qax_result;
}

inline int _DeXCom::SetJis8Item(int lMsgId, const QString& pszValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pszValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 59, _a);
    return qax_result;
}

inline int _DeXCom::SetListItem(int lMsgId, int nItems)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&nItems};
    qt_metacall(QMetaObject::InvokeMetaMethod, 60, _a);
    return qax_result;
}

inline int _DeXCom::SetMsgBytes(int lMsgId, int& pnMsg, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnMsg, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 61, _a);
    return qax_result;
}

inline int _DeXCom::SetParam(const QString& psParamName, const QString& psVal)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&psParamName, (void*)&psVal};
    qt_metacall(QMetaObject::InvokeMetaMethod, 64, _a);
    return qax_result;
}

inline int _DeXCom::SetStringItem(int lMsgId, QString& pbstrValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pbstrValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 68, _a);
    return qax_result;
}

inline int _DeXCom::SetU1Item(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 70, _a);
    return qax_result;
}

inline int _DeXCom::SetU2Item(int lMsgId, int& plValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 71, _a);
    return qax_result;
}

inline int _DeXCom::SetU4Item(int lMsgId, double& prValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 72, _a);
    return qax_result;
}

inline int _DeXCom::SetU8Item(int lMsgId, double& prValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 73, _a);
    return qax_result;
}

inline int _DeXCom::SetWBit(int lMsgId, int nWBit)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&nWBit};
    qt_metacall(QMetaObject::InvokeMetaMethod, 74, _a);
    return qax_result;
}

inline int _DeXCom::Start()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 76, _a);
    return qax_result;
}

inline int _DeXCom::Stop()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 77, _a);
    return qax_result;
}


inline int eXCom::Block() const
{
    QVariant qax_result = property("Block");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetBlock(int value){ setProperty("Block", QVariant(value)); }

inline int eXCom::DeviceID() const
{
    QVariant qax_result = property("DeviceID");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetDeviceID(int value){ setProperty("DeviceID", QVariant(value)); }

inline int eXCom::Ebit() const
{
    QVariant qax_result = property("Ebit");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetEbit(int value){ setProperty("Ebit", QVariant(value)); }

inline int eXCom::Function() const
{
    QVariant qax_result = property("Function");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetFunction(int value){ setProperty("Function", QVariant(value)); }

inline int eXCom::HeaderSize() const
{
    QVariant qax_result = property("HeaderSize");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetHeaderSize(int value){ setProperty("HeaderSize", QVariant(value)); }

inline int eXCom::MsgSize() const
{
    QVariant qax_result = property("MsgSize");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetMsgSize(int value){ setProperty("MsgSize", QVariant(value)); }

inline int eXCom::PType() const
{
    QVariant qax_result = property("PType");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetPType(int value){ setProperty("PType", QVariant(value)); }

inline int eXCom::Rbit() const
{
    QVariant qax_result = property("Rbit");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetRbit(int value){ setProperty("Rbit", QVariant(value)); }

inline int eXCom::SType() const
{
    QVariant qax_result = property("SType");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetSType(int value){ setProperty("SType", QVariant(value)); }

inline int eXCom::Stream() const
{
    QVariant qax_result = property("Stream");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetStream(int value){ setProperty("Stream", QVariant(value)); }

inline int eXCom::SystemBytes() const
{
    QVariant qax_result = property("SystemBytes");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetSystemBytes(int value){ setProperty("SystemBytes", QVariant(value)); }

inline int eXCom::Wbit() const
{
    QVariant qax_result = property("Wbit");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void eXCom::SetWbit(int value){ setProperty("Wbit", QVariant(value)); }

inline int eXCom::Close()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 32, _a);
    return qax_result;
}

inline void eXCom::CloseSecsMsg(int lMsgId)
{
    void *_a[] = {0, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 33, _a);
}

inline int eXCom::DebugInfo(int& pnInfo)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pnInfo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 34, _a);
    return qax_result;
}

inline int eXCom::EnableLog(int nLogType, int nEnabled)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nLogType, (void*)&nEnabled};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
    return qax_result;
}

inline int eXCom::GeneralCall(int lMsgId, int nDispatchId, int lpDispatchData, int lDispatchArg1, int lDispatchArg2)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&nDispatchId, (void*)&lpDispatchData, (void*)&lDispatchArg1, (void*)&lDispatchArg2};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
    return qax_result;
}

inline int eXCom::GetAlarmMsgInfo(int lMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnDevId, (void*)&pnStrm, (void*)&pnFunc, (void*)&plSysByte, (void*)&pnWbit};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline int eXCom::GetAsciiItem(int lMsgId, QString& psValue, int& plCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&psValue, (void*)&plCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline int eXCom::GetBinaryItem(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline int eXCom::GetBoolItem(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline int eXCom::GetCurrentItemCount(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline int eXCom::GetCurrentItemType(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline int eXCom::GetF4Item(int lMsgId, double& prValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
    return qax_result;
}

inline int eXCom::GetF8Item(int lMsgId, double& prValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
    return qax_result;
}

inline int eXCom::GetHeaderBytes(int lMsgId, int& pnHeader, int nSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnHeader, (void*)&nSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
    return qax_result;
}

inline int eXCom::GetI1Item(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
    return qax_result;
}

inline int eXCom::GetI2Item(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
    return qax_result;
}

inline int eXCom::GetI4Item(int lMsgId, int& plValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
    return qax_result;
}

inline int eXCom::GetI8Item(int lMsgId, int& plValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
    return qax_result;
}

inline int eXCom::GetInvalidMsgInfo(int lMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnDevId, (void*)&pnStrm, (void*)&pnFunc, (void*)&plSysByte, (void*)&pnWbit};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
    return qax_result;
}

inline int eXCom::GetJis8Item(int lMsgId, QString& psValue, int& plCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&psValue, (void*)&plCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
    return qax_result;
}

inline int eXCom::GetListItem(int lMsgId, int& pnItems)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnItems};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
    return qax_result;
}

inline int eXCom::GetMsgBytes(int lMsgId, int& pnMsg, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnMsg, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
    return qax_result;
}

inline QString eXCom::GetParam(const QString& pszParamName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pszParamName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 54, _a);
    return qax_result;
}

inline QString eXCom::GetSecsLog(int lMsgId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 55, _a);
    return qax_result;
}

inline QString eXCom::GetStringItem(int lMsgId, int& plCount)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 56, _a);
    return qax_result;
}

inline int eXCom::GetSysBytes(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
    return qax_result;
}

inline int eXCom::GetU1Item(int lMsgId, int& pnValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 58, _a);
    return qax_result;
}

inline int eXCom::GetU2Item(int lMsgId, int& plValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 59, _a);
    return qax_result;
}

inline int eXCom::GetU4Item(int lMsgId, double& prValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 60, _a);
    return qax_result;
}

inline int eXCom::GetU8Item(int lMsgId, double& prValue, int& plCount, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&plCount, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 61, _a);
    return qax_result;
}

inline int eXCom::Initialize(const QString& sCfgFile)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&sCfgFile};
    qt_metacall(QMetaObject::InvokeMetaMethod, 62, _a);
    return qax_result;
}

inline int eXCom::LoadSecsMsg(int& plMsgId, int& pnDevId, int& pnStrm, int& pnFunc, int& plSysByte, int& pnWbit)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&plMsgId, (void*)&pnDevId, (void*)&pnStrm, (void*)&pnFunc, (void*)&plSysByte, (void*)&pnWbit};
    qt_metacall(QMetaObject::InvokeMetaMethod, 63, _a);
    return qax_result;
}

inline int eXCom::MakeSecsMsg(int& plMsgId, int nDevId, int nStrm, int nFunc, int lSysByte)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&plMsgId, (void*)&nDevId, (void*)&nStrm, (void*)&nFunc, (void*)&lSysByte};
    qt_metacall(QMetaObject::InvokeMetaMethod, 64, _a);
    return qax_result;
}

inline int eXCom::MakeSpoolStream(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 65, _a);
    return qax_result;
}

inline int eXCom::ProcExternalStream(int& pnMsg, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pnMsg, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 66, _a);
    return qax_result;
}

inline int eXCom::Send(int lMsgId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 67, _a);
    return qax_result;
}

inline int eXCom::SetAsciiFillSpace(int nVal)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&nVal};
    qt_metacall(QMetaObject::InvokeMetaMethod, 68, _a);
    return qax_result;
}

inline int eXCom::SetAsciiItem(int lMsgId, const QString& pszValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pszValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 69, _a);
    return qax_result;
}

inline int eXCom::SetBinaryItem(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 70, _a);
    return qax_result;
}

inline int eXCom::SetBoolItem(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 72, _a);
    return qax_result;
}

inline int eXCom::SetF4Item(int lMsgId, double& prValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 75, _a);
    return qax_result;
}

inline int eXCom::SetF8Item(int lMsgId, double& prValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 76, _a);
    return qax_result;
}

inline int eXCom::SetHeaderBytes(int lMsgId, int& pnHeader, int nSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnHeader, (void*)&nSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 78, _a);
    return qax_result;
}

inline int eXCom::SetI1Item(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 80, _a);
    return qax_result;
}

inline int eXCom::SetI2Item(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 81, _a);
    return qax_result;
}

inline int eXCom::SetI4Item(int lMsgId, int& plValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 82, _a);
    return qax_result;
}

inline int eXCom::SetI8Item(int lMsgId, int& plValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 83, _a);
    return qax_result;
}

inline int eXCom::SetJis8Item(int lMsgId, const QString& pszValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pszValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 84, _a);
    return qax_result;
}

inline int eXCom::SetListItem(int lMsgId, int nItems)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&nItems};
    qt_metacall(QMetaObject::InvokeMetaMethod, 85, _a);
    return qax_result;
}

inline int eXCom::SetMsgBytes(int lMsgId, int& pnMsg, int lSize)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnMsg, (void*)&lSize};
    qt_metacall(QMetaObject::InvokeMetaMethod, 86, _a);
    return qax_result;
}

inline int eXCom::SetParam(const QString& psParamName, const QString& psVal)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&psParamName, (void*)&psVal};
    qt_metacall(QMetaObject::InvokeMetaMethod, 89, _a);
    return qax_result;
}

inline int eXCom::SetStringItem(int lMsgId, QString& pbstrValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pbstrValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 93, _a);
    return qax_result;
}

inline int eXCom::SetU1Item(int lMsgId, int& pnValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&pnValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 95, _a);
    return qax_result;
}

inline int eXCom::SetU2Item(int lMsgId, int& plValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&plValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 96, _a);
    return qax_result;
}

inline int eXCom::SetU4Item(int lMsgId, double& prValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 97, _a);
    return qax_result;
}

inline int eXCom::SetU8Item(int lMsgId, double& prValue, int lCount)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&prValue, (void*)&lCount};
    qt_metacall(QMetaObject::InvokeMetaMethod, 98, _a);
    return qax_result;
}

inline int eXCom::SetWBit(int lMsgId, int nWBit)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&lMsgId, (void*)&nWBit};
    qt_metacall(QMetaObject::InvokeMetaMethod, 99, _a);
    return qax_result;
}

inline int eXCom::Start()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 101, _a);
    return qax_result;
}

inline int eXCom::Stop()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 102, _a);
    return qax_result;
}



#endif

}

template<>
inline void *qMetaTypeConstructHelper(const EXCOMLib::_DeXCom *t)
{ Q_ASSERT(!t); return new EXCOMLib::_DeXCom; }

template<>
inline void *qMetaTypeConstructHelper(const EXCOMLib::eXCom *t)
{ Q_ASSERT(!t); return new EXCOMLib::eXCom; }

#endif

