/****************************************************************************
**
** Metadata for EXCOMVBLib generated by dumpcpp from type library
** eXComVb.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_EXCOMVBLIB_NOINLINES
#include "excomvblib.h"

using namespace EXCOMVBLib;

static const uint qt_meta_data_EXCOMVBLib___DXComVb[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       66,    10, // methods
       48,    340, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       21, 60, 82, 83, 5,
       84, 109, 114, 115, 5,
       116, 142, 157, 158, 5,

 // slots: signature, parameters, type, tag, flags
       159, 167, 168, 172, 9,
       173, 188, 189, 190, 9,
       191, 207, 214, 218, 9,
       219, 240, 247, 251, 9,
       252, 275, 282, 286, 9,
       287, 305, 317, 325, 9,
       326, 343, 344, 352, 9,
       353, 370, 371, 379, 9,
       380, 400, 409, 413, 9,
       414, 428, 429, 433, 9,
       434, 463, 500, 504, 9,
       505, 512, 513, 517, 9,
       518, 536, 542, 543, 9,
       544, 567, 572, 576, 9,
       577, 592, 599, 600, 9,
       601, 615, 620, 621, 9,
       622, 646, 661, 662, 9,
       663, 687, 702, 703, 9,
       704, 727, 741, 742, 9,
       743, 767, 782, 783, 9,
       784, 798, 801, 802, 9,
       803, 817, 820, 821, 9,
       822, 841, 852, 853, 9,
       854, 873, 884, 885, 9,
       886, 897, 900, 901, 9,
       902, 913, 916, 917, 9,
       918, 929, 932, 933, 9,
       934, 945, 948, 949, 9,
       950, 968, 978, 979, 9,
       980, 997, 1002, 1003, 9,
       1004, 1017, 1022, 1023, 9,
       1024, 1040, 1048, 1049, 9,
       1050, 1066, 1074, 1075, 9,
       1076, 1093, 1102, 1103, 9,
       1104, 1130, 1148, 1152, 9,
       1153, 1168, 1175, 1176, 9,
       1177, 1195, 1205, 1206, 9,
       1207, 1221, 1227, 1228, 9,
       1229, 1247, 1257, 1258, 9,
       1259, 1274, 1281, 1282, 9,
       1283, 1298, 1305, 1306, 9,
       1307, 1321, 1327, 1328, 9,
       1329, 1344, 1351, 1352, 9,
       1353, 1369, 1377, 1378, 9,
       1379, 1400, 1413, 1414, 9,
       1415, 1429, 1435, 1436, 9,
       1437, 1452, 1459, 1460, 9,
       1461, 1479, 1489, 1490, 9,
       1491, 1505, 1511, 1512, 9,
       1513, 1531, 1541, 1542, 9,
       1543, 1558, 1565, 1566, 9,
       1567, 1582, 1589, 1590, 9,
       1591, 1605, 1611, 1612, 9,
       1613, 1628, 1635, 1636, 9,
       1637, 1653, 1661, 1662, 9,
       1663, 1684, 1697, 1698, 9,
       1699, 1713, 1719, 1720, 9,
       1721, 1732, 1735, 1736, 9,
       1737, 1748, 1751, 1752, 9,
       1753, 1767, 1770, 1771, 9,
       1772, 1786, 1789, 1790, 9,
       1791, 1799, 1800, 1804, 9,
       1805, 1812, 1813, 1817, 9,

 // properties: name, type, flags
       1818, 1824, 0x0a015003, 		 // QString Ascii
       1832, 1839, 0x02015003, 		 // int Binary
       1843, 1848, 0x01015003, 		 // bool Bool
       1853, 1868, 0x01015003, 		 // bool EnableAlarmLog
       1873, 1888, 0x01015003, 		 // bool EnableEventLog
       1893, 1907, 0x01015003, 		 // bool EnableHexaLog
       1912, 1927, 0x01015003, 		 // bool EnableSecs2Log
       1932, 1935, 0x06015003, 		 // double F4
       1942, 1945, 0x06015003, 		 // double F8
       1952, 1963, 0x02015003, 		 // int HeaderByte
       1967, 1978, 0x02015003, 		 // int HeaderSize
       1982, 1985, 0x02015003, 		 // int I1
       1989, 1992, 0x02015003, 		 // int I2
       1996, 1999, 0x02015003, 		 // int I4
       2003, 2006, 0x02015003, 		 // int I8
       2010, 2020, 0x02015003, 		 // int ItemCount
       2024, 2029, 0x0a015003, 		 // QString Jis8
       2037, 2042, 0x02015003, 		 // int List
       2046, 2054, 0x02015003, 		 // int MsgByte
       2058, 2066, 0x02015003, 		 // int MsgSize
       2070, 2079, 0x02015003, 		 // int NextItem
       2083, 2090, 0x02015003, 		 // int RBlock
       2094, 2104, 0x02015003, 		 // int RDeviceId
       2108, 2114, 0x02015003, 		 // int REbit
       2118, 2128, 0x02015003, 		 // int RFunction
       2132, 2139, 0x02015003, 		 // int RMsgId
       2143, 2150, 0x02015003, 		 // int RPType
       2154, 2160, 0x02015003, 		 // int RRbit
       2164, 2171, 0x02015003, 		 // int RSType
       2175, 2183, 0x02015003, 		 // int RStream
       2187, 2200, 0x02015003, 		 // int RSystemBytes
       2204, 2210, 0x02015003, 		 // int RWbit
       2214, 2221, 0x02015003, 		 // int SBlock
       2225, 2235, 0x02015003, 		 // int SDeviceId
       2239, 2245, 0x02015003, 		 // int SEbit
       2249, 2259, 0x02015003, 		 // int SFunction
       2263, 2270, 0x02015003, 		 // int SMsgId
       2274, 2281, 0x02015003, 		 // int SPType
       2285, 2291, 0x02015003, 		 // int SRbit
       2295, 2302, 0x02015003, 		 // int SSType
       2306, 2314, 0x02015003, 		 // int SStream
       2318, 2331, 0x02015003, 		 // int SSystemBytes
       2335, 2341, 0x02015003, 		 // int SWbit
       2345, 2348, 0x02015003, 		 // int U1
       2352, 2355, 0x02015003, 		 // int U2
       2359, 2362, 0x06015003, 		 // double U4
       2369, 2372, 0x06015003, 		 // double U8
       2379, 2387, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_EXCOMVBLib___DXComVb() {
    static const char stringdata0[] = {
    "EXCOMVBLib::_DXComVb\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Close()\0\0int\0\0CloseSecsMsg()\0\0\0\0DebugInfo(int&)\0pnInfo\0int\0\0GetAlarmMsgInfo(int)\0"
    "lMsgId\0int\0\0GetInvalidMsgInfo(int)\0lMsgId\0int\0\0GetParam(QString)\0psParamName\0QString\0\0GetRMsgSecsLog()\0\0QString\0\0GetSMsgSecsLog()\0\0QString\0\0Initialize(QString)\0sCfgFile\0int\0\0LoadSecsMsg()\0\0int\0\0MakeSecsMsg(int,int,int,int)\0"
    "nDeviceId,nStream,nFunction,lSysByte\0int\0\0Send()\0\0int\0\0SetAscii(QString)\0Ascii\0\0\0SetAsciiFillSpace(int)\0nVal\0int\0\0SetBinary(int)\0Binary\0\0\0SetBool(bool)\0Bool\0\0\0SetEnableAlarmLog(bool)\0EnableAlarmLog\0\0\0SetEnableEventLog(bool)\0"
    "EnableEventLog\0\0\0SetEnableHexaLog(bool)\0EnableHexaLog\0\0\0SetEnableSecs2Log(bool)\0EnableSecs2Log\0\0\0SetF4(double)\0F4\0\0\0SetF8(double)\0F8\0\0\0SetHeaderByte(int)\0HeaderByte\0\0\0SetHeaderSize(int)\0HeaderSize\0\0\0SetI1(int)\0"
    "I1\0\0\0SetI2(int)\0I2\0\0\0SetI4(int)\0I4\0\0\0SetI8(int)\0I8\0\0\0SetItemCount(int)\0ItemCount\0\0\0SetJis8(QString)\0Jis8\0\0\0SetList(int)\0List\0\0\0SetMsgByte(int)\0MsgByte\0\0\0SetMsgSize(int)\0MsgSize\0\0\0SetNextItem(int)\0NextItem\0"
    "\0\0SetParam(QString,QString)\0psParamName,psVal\0int\0\0SetRBlock(int)\0RBlock\0\0\0SetRDeviceId(int)\0RDeviceId\0\0\0SetREbit(int)\0REbit\0\0\0SetRFunction(int)\0RFunction\0\0\0SetRMsgId(int)\0RMsgId\0\0\0SetRPType(int)\0RPType\0"
    "\0\0SetRRbit(int)\0RRbit\0\0\0SetRSType(int)\0RSType\0\0\0SetRStream(int)\0RStream\0\0\0SetRSystemBytes(int)\0RSystemBytes\0\0\0SetRWbit(int)\0RWbit\0\0\0SetSBlock(int)\0SBlock\0\0\0SetSDeviceId(int)\0SDeviceId\0\0\0SetSEbit(int)\0SEbit\0"
    "\0\0SetSFunction(int)\0SFunction\0\0\0SetSMsgId(int)\0SMsgId\0\0\0SetSPType(int)\0SPType\0\0\0SetSRbit(int)\0SRbit\0\0\0SetSSType(int)\0SSType\0\0\0SetSStream(int)\0SStream\0\0\0SetSSystemBytes(int)\0SSystemBytes\0\0\0SetSWbit(int)\0"
    "SWbit\0\0\0SetU1(int)\0U1\0\0\0SetU2(int)\0U2\0\0\0SetU4(double)\0U4\0\0\0SetU8(double)\0U8\0\0\0Start()\0\0int\0\0Stop()\0\0int\0\0"
    "Ascii\0QString\0Binary\0int\0Bool\0bool\0EnableAlarmLog\0bool\0EnableEventLog\0bool\0EnableHexaLog\0bool\0EnableSecs2Log\0"
    "bool\0F4\0double\0F8\0double\0HeaderByte\0int\0HeaderSize\0int\0I1\0int\0I2\0int\0I4\0int\0I8\0int\0ItemCount\0int\0Jis8\0QString\0List\0int\0MsgByte\0int\0MsgSize\0int\0NextItem\0int\0RBlock\0int\0RDeviceId\0int\0REbit\0int\0RFunction\0"
    "int\0RMsgId\0int\0RPType\0int\0RRbit\0int\0RSType\0int\0RStream\0int\0RSystemBytes\0int\0RWbit\0int\0SBlock\0int\0SDeviceId\0int\0SEbit\0int\0SFunction\0int\0SMsgId\0int\0SPType\0int\0SRbit\0int\0SSType\0int\0SStream\0int\0SSystemBytes\0"
    "int\0SWbit\0int\0U1\0int\0U2\0int\0U4\0double\0U8\0double\0control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject _DXComVb::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_EXCOMVBLib___DXComVb(),
qt_meta_data_EXCOMVBLib___DXComVb }
};

void *_DXComVb::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_EXCOMVBLib___DXComVb()))
        return static_cast<void*>(const_cast<_DXComVb*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_EXCOMVBLib__XComVb[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       68,    12, // methods
       47,    352, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       19, 37, 

 // signals: signature, parameters, type, tag, flags
       52, 71, 87, 88, 5,
       89, 99, 100, 101, 5,
       102, 141, 163, 164, 5,
       165, 190, 195, 196, 5,
       197, 223, 238, 239, 5,

 // slots: signature, parameters, type, tag, flags
       240, 248, 249, 253, 9,
       254, 269, 270, 271, 9,
       272, 288, 295, 299, 9,
       300, 321, 328, 332, 9,
       333, 356, 363, 367, 9,
       368, 386, 398, 406, 9,
       407, 424, 425, 433, 9,
       434, 451, 452, 460, 9,
       461, 481, 490, 494, 9,
       495, 509, 510, 514, 9,
       515, 544, 581, 585, 9,
       586, 593, 594, 598, 9,
       599, 617, 623, 624, 9,
       625, 648, 653, 657, 9,
       658, 673, 680, 681, 9,
       682, 696, 701, 702, 9,
       703, 727, 742, 743, 9,
       744, 768, 783, 784, 9,
       785, 808, 822, 823, 9,
       824, 848, 863, 864, 9,
       865, 879, 882, 883, 9,
       884, 898, 901, 902, 9,
       903, 922, 933, 934, 9,
       935, 954, 965, 966, 9,
       967, 978, 981, 982, 9,
       983, 994, 997, 998, 9,
       999, 1010, 1013, 1014, 9,
       1015, 1026, 1029, 1030, 9,
       1031, 1049, 1059, 1060, 9,
       1061, 1078, 1083, 1084, 9,
       1085, 1098, 1103, 1104, 9,
       1105, 1121, 1129, 1130, 9,
       1131, 1147, 1155, 1156, 9,
       1157, 1174, 1183, 1184, 9,
       1185, 1211, 1229, 1233, 9,
       1234, 1249, 1256, 1257, 9,
       1258, 1276, 1286, 1287, 9,
       1288, 1302, 1308, 1309, 9,
       1310, 1328, 1338, 1339, 9,
       1340, 1355, 1362, 1363, 9,
       1364, 1379, 1386, 1387, 9,
       1388, 1402, 1408, 1409, 9,
       1410, 1425, 1432, 1433, 9,
       1434, 1450, 1458, 1459, 9,
       1460, 1481, 1494, 1495, 9,
       1496, 1510, 1516, 1517, 9,
       1518, 1533, 1540, 1541, 9,
       1542, 1560, 1570, 1571, 9,
       1572, 1586, 1592, 1593, 9,
       1594, 1612, 1622, 1623, 9,
       1624, 1639, 1646, 1647, 9,
       1648, 1663, 1670, 1671, 9,
       1672, 1686, 1692, 1693, 9,
       1694, 1709, 1716, 1717, 9,
       1718, 1734, 1742, 1743, 9,
       1744, 1765, 1778, 1779, 9,
       1780, 1794, 1800, 1801, 9,
       1802, 1813, 1816, 1817, 9,
       1818, 1829, 1832, 1833, 9,
       1834, 1848, 1851, 1852, 9,
       1853, 1867, 1870, 1871, 9,
       1872, 1880, 1881, 1885, 9,
       1886, 1893, 1894, 1898, 9,

 // properties: name, type, flags
       1899, 1905, 0x0a015003, 		 // QString Ascii
       1913, 1920, 0x02015003, 		 // int Binary
       1924, 1929, 0x01015003, 		 // bool Bool
       1934, 1949, 0x01015003, 		 // bool EnableAlarmLog
       1954, 1969, 0x01015003, 		 // bool EnableEventLog
       1974, 1988, 0x01015003, 		 // bool EnableHexaLog
       1993, 2008, 0x01015003, 		 // bool EnableSecs2Log
       2013, 2016, 0x06015003, 		 // double F4
       2023, 2026, 0x06015003, 		 // double F8
       2033, 2044, 0x02015003, 		 // int HeaderByte
       2048, 2059, 0x02015003, 		 // int HeaderSize
       2063, 2066, 0x02015003, 		 // int I1
       2070, 2073, 0x02015003, 		 // int I2
       2077, 2080, 0x02015003, 		 // int I4
       2084, 2087, 0x02015003, 		 // int I8
       2091, 2101, 0x02015003, 		 // int ItemCount
       2105, 2110, 0x0a015003, 		 // QString Jis8
       2118, 2123, 0x02015003, 		 // int List
       2127, 2135, 0x02015003, 		 // int MsgByte
       2139, 2147, 0x02015003, 		 // int MsgSize
       2151, 2160, 0x02015003, 		 // int NextItem
       2164, 2171, 0x02015003, 		 // int RBlock
       2175, 2185, 0x02015003, 		 // int RDeviceId
       2189, 2195, 0x02015003, 		 // int REbit
       2199, 2209, 0x02015003, 		 // int RFunction
       2213, 2220, 0x02015003, 		 // int RMsgId
       2224, 2231, 0x02015003, 		 // int RPType
       2235, 2241, 0x02015003, 		 // int RRbit
       2245, 2252, 0x02015003, 		 // int RSType
       2256, 2264, 0x02015003, 		 // int RStream
       2268, 2281, 0x02015003, 		 // int RSystemBytes
       2285, 2291, 0x02015003, 		 // int RWbit
       2295, 2302, 0x02015003, 		 // int SBlock
       2306, 2316, 0x02015003, 		 // int SDeviceId
       2320, 2326, 0x02015003, 		 // int SEbit
       2330, 2340, 0x02015003, 		 // int SFunction
       2344, 2351, 0x02015003, 		 // int SMsgId
       2355, 2362, 0x02015003, 		 // int SPType
       2366, 2372, 0x02015003, 		 // int SRbit
       2376, 2383, 0x02015003, 		 // int SSType
       2387, 2395, 0x02015003, 		 // int SStream
       2399, 2412, 0x02015003, 		 // int SSystemBytes
       2416, 2422, 0x02015003, 		 // int SWbit
       2426, 2429, 0x02015003, 		 // int U1
       2433, 2436, 0x02015003, 		 // int U2
       2440, 2443, 0x06015003, 		 // double U4
       2450, 2453, 0x06015003, 		 // double U8

        0        // eod
};

static const char *qt_meta_stringdata_EXCOMVBLib__XComVb() {
    static const char stringdata0[] = {
    "EXCOMVBLib::XComVb\0"
    "Event Interface 1\0_DXComVbEvents\0"
    "SecsEvent(int,int)\0nEventId,lParam\0\0\0SecsMsg()\0\0\0\0exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0"
    "name,argc,argv\0\0\0"
    "Close()\0\0int\0\0CloseSecsMsg()\0\0\0\0DebugInfo(int&)\0pnInfo\0int\0\0GetAlarmMsgInfo(int)\0lMsgId\0int\0\0GetInvalidMsgInfo(int)\0lMsgId\0int\0\0GetParam(QString)\0psParamName\0QString\0\0GetRMsgSecsLog()\0"
    "\0QString\0\0GetSMsgSecsLog()\0\0QString\0\0Initialize(QString)\0sCfgFile\0int\0\0LoadSecsMsg()\0\0int\0\0MakeSecsMsg(int,int,int,int)\0nDeviceId,nStream,nFunction,lSysByte\0int\0\0Send()\0\0int\0\0SetAscii(QString)\0Ascii\0\0\0"
    "SetAsciiFillSpace(int)\0nVal\0int\0\0SetBinary(int)\0Binary\0\0\0SetBool(bool)\0Bool\0\0\0SetEnableAlarmLog(bool)\0EnableAlarmLog\0\0\0SetEnableEventLog(bool)\0EnableEventLog\0\0\0SetEnableHexaLog(bool)\0EnableHexaLog\0\0\0SetEnableSecs2Log(bool)\0"
    "EnableSecs2Log\0\0\0SetF4(double)\0F4\0\0\0SetF8(double)\0F8\0\0\0SetHeaderByte(int)\0HeaderByte\0\0\0SetHeaderSize(int)\0HeaderSize\0\0\0SetI1(int)\0I1\0\0\0SetI2(int)\0I2\0\0\0SetI4(int)\0I4\0\0\0SetI8(int)\0I8\0\0\0SetItemCount(int)\0"
    "ItemCount\0\0\0SetJis8(QString)\0Jis8\0\0\0SetList(int)\0List\0\0\0SetMsgByte(int)\0MsgByte\0\0\0SetMsgSize(int)\0MsgSize\0\0\0SetNextItem(int)\0NextItem\0\0\0SetParam(QString,QString)\0psParamName,psVal\0int\0\0SetRBlock(int)\0RBlock\0"
    "\0\0SetRDeviceId(int)\0RDeviceId\0\0\0SetREbit(int)\0REbit\0\0\0SetRFunction(int)\0RFunction\0\0\0SetRMsgId(int)\0RMsgId\0\0\0SetRPType(int)\0RPType\0\0\0SetRRbit(int)\0RRbit\0\0\0SetRSType(int)\0RSType\0\0\0SetRStream(int)\0RStream\0"
    "\0\0SetRSystemBytes(int)\0RSystemBytes\0\0\0SetRWbit(int)\0RWbit\0\0\0SetSBlock(int)\0SBlock\0\0\0SetSDeviceId(int)\0SDeviceId\0\0\0SetSEbit(int)\0SEbit\0\0\0SetSFunction(int)\0SFunction\0\0\0SetSMsgId(int)\0SMsgId\0\0\0SetSPType(int)\0"
    "SPType\0\0\0SetSRbit(int)\0SRbit\0\0\0SetSSType(int)\0SSType\0\0\0SetSStream(int)\0SStream\0\0\0SetSSystemBytes(int)\0SSystemBytes\0\0\0SetSWbit(int)\0SWbit\0\0\0SetU1(int)\0U1\0\0\0SetU2(int)\0U2\0\0\0SetU4(double)\0U4\0\0\0SetU8(double)\0"
    "U8\0\0\0Start()\0\0int\0\0Stop()\0\0int\0\0"
    "Ascii\0QString\0Binary\0int\0Bool\0bool\0EnableAlarmLog\0bool\0EnableEventLog\0bool\0EnableHexaLog\0bool\0EnableSecs2Log\0bool\0F4\0double\0F8\0double\0HeaderByte\0int\0HeaderSize\0int\0I1\0int\0"
    "I2\0int\0I4\0int\0I8\0int\0ItemCount\0int\0Jis8\0QString\0List\0int\0MsgByte\0int\0MsgSize\0int\0NextItem\0int\0RBlock\0int\0RDeviceId\0int\0REbit\0int\0RFunction\0int\0RMsgId\0int\0RPType\0int\0RRbit\0int\0RSType\0int\0RStream\0int\0RSystemBytes\0"
    "int\0RWbit\0int\0SBlock\0int\0SDeviceId\0int\0SEbit\0int\0SFunction\0int\0SMsgId\0int\0SPType\0int\0SRbit\0int\0SSType\0int\0SStream\0int\0SSystemBytes\0int\0SWbit\0int\0U1\0int\0U2\0int\0U4\0double\0U8\0double\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject XComVb::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_EXCOMVBLib__XComVb(),
qt_meta_data_EXCOMVBLib__XComVb }
};

void *XComVb::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_EXCOMVBLib__XComVb()))
        return static_cast<void*>(const_cast<XComVb*>(this));
    return QAxWidget::qt_metacast(_clname);
}

